Added guards around invalid env values

diff --git a/.github/workflows/deploy-api.yaml b/.github/workflows/deploy-api.yaml
--- a/.github/workflows/deploy-api.yaml
+++ b/.github/workflows/deploy-api.yaml
@@ -26,7 +26,14 @@ jobs:
             -
                 name: "Deploy to ${{ github.event.inputs.environment }}"
                 run: |
-                    echo "Deploying to ${{ github.event.inputs.environment }}"
+                    if [ "${{ github.event.inputs.environment }}" = "test" ]; then
+                        echo "Deploying to test"
+                    elif [ "${{ github.event.inputs.environment }}" = "prod" ]; then
+                        echo "Deploying to prod"
+                    else
+                        echo "Invalid environment"
+                        exit 1
+                    fi
             - 
                 name: "Setup node"
                 uses: "actions/setup-node@v4"
